// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/notifications/InAppList.tsx": () => import("../components/mockups/notifications/InAppList.tsx"),
  "./components/mockups/notifications/LockScreen.tsx": () => import("../components/mockups/notifications/LockScreen.tsx")
};
